### ISSUE TITLE
AppChooser Portal

### ISSUE THREAD

**Issue by danrabbit** [elementary/xdg-desktop-portal-pantheon#8]
## Problem

The current app chooser portal has some GNOME specific things like links to GNOME Software

## Proposal

Make a new one

**Comment by Marukesu** [comment]
So, I did this on the weekend:
![AppChooser Dialog](https://user-images.githubusercontent.com/21296444/121955362-3d947680-cd36-11eb-9202-1b18c91d3e2d.png)

it's using libhandy, so it's a one more dependency.
The first app is always the last used. since it's a carousel, to evite opening a wrong application, clicking a icon only select it.

There isn't a show all option because i don't know if the portal frontend allow passing a app id that is not on the choices list.

**Comment by danrabbit** [comment]
@Marukesu hey that's super cute! Definitely open a PR :)
